# Generated by Django 5.2.4 on 2025-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='lender',
            field=models.CharField(max_length=255, verbose_name='Creditor (Who you must pay)'),
        ),
    ]
