# Generated by Django 5.2.4 on 2025-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='date',
            field=models.DateField(),
        ),
    ]
