# Generated by Django 5.2.4 on 2025-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_budget_last_alert'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(blank=True, to='accounts.category'),
        ),
    ]
