# Generated by Django 5.2.4 on 2025-11-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_budget_last_alert'),
        ('expenses', '0002_remove_expense_category_expense_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='expenses', to='accounts.category'),
        ),
    ]
