# Generated by Django 5.2.4 on 2025-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='merchant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='categories',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
