# Generated by Django 5.2.4 on 2025-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_budget_category_budget_categories'),
        ('expenses', '0004_expense_merchant_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='categories',
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(blank=True, to='accounts.category'),
        ),
    ]
