# Generated by Django 5.2.4 on 2025-12-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_expense_categories_expense_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expense')),
            ],
        ),
    ]
