# Generated by Django 5.2.4 on 2025-12-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_category_user'),
        ('expenses', '0006_remove_expense_amount_remove_expense_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='category',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='categories',
            field=models.ManyToManyField(blank=True, to='accounts.category'),
        ),
    ]
