# Generated by Django 5.2.4 on 2025-12-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_expenseitem_category_expenseitem_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='total_amount',
        ),
    ]
