# Generated by Django 5.2.4 on 2025-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_category_user_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_alert',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
