# Generated by Django 5.2.5 on 2025-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_budget_last_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(related_name='budgets', to='accounts.category'),
        ),
    ]
