# Generated by Django 5.2.4 on 2025-12-03 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='limit_amount',
            new_name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='last_alert',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='spent',
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
