# Generated by Django 5.2.4 on 2025-12-03 12:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_limit_amount_budget_monthly_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinancialGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income_goal', models.DecimalField(decimal_places=2, default=100000.0, help_text='Your target monthly income (Rs.)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_expense_limit', models.DecimalField(decimal_places=2, default=60000.0, help_text='Maximum allowed monthly expense (Rs.)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_saving_goal', models.DecimalField(decimal_places=2, default=30000.0, help_text='Target monthly savings (Rs.)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_debt_limit', models.DecimalField(decimal_places=2, default=20000.0, help_text='Maximum acceptable total debt (Rs.)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Goal',
                'verbose_name_plural': 'Financial Goals',
            },
        ),
    ]
